apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
