apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  namespace: default
spec:
  storageClassName: local-storage
  claimRef:
    name: keycloak-volume
    namespace: default
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/
  nodeAffinity:
   required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - node01
